-- Existing batches may use either:
--   1. The legacy "EXP-{yyyy-MM}-{LASTNAME}" format generated by the now-removed
--      iOS bundleInvoice flow, or
--   2. The canonical "EXP-BATCH-NNNN" format from this Postgres function.
-- The function was casting EVERY batch_number's "after the EXP-BATCH- prefix"
-- segment to INT, which throws on legacy rows like "EXP-2026-04-VALORANT".
-- Filter to canonical-format rows only — the two namespaces co-exist
-- without collision.

create or replace function public.get_next_expense_batch_number(p_company_id uuid)
returns text
language plpgsql
as $function$
declare
    next_num int;
    result   text;
begin
    select coalesce(max(
        cast(replace(batch_number, 'EXP-BATCH-', '') as int)
    ), 0) + 1
    into next_num
    from expense_batches
    where company_id = p_company_id
      and batch_number ~ '^EXP-BATCH-[0-9]+$';

    result := 'EXP-BATCH-' || lpad(next_num::text, 4, '0');
    return result;
end;
$function$;
