ALTER TABLE clients ADD COLUMN IF NOT EXISTS sage_id TEXT;
ALTER TABLE estimates ADD COLUMN IF NOT EXISTS sage_id TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS sage_id TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS sage_id TEXT;
